name: "Github Release with Artifact Fix"
author: "Richard Brežák"
branding:
  icon: "git-branch"
  color: "gray-dark"
description: "Publish Github releases from an action"

inputs:
  title:
    description: "The name of the release to publish"
    required: true
  workdir:
    description: "Directory of the repository that the should create the release"
    required: false

runs:
  using: 'composite'
  steps:      
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
